"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Mark } from "./mark";
import { ListChecks, UserRound, Compass, Plane, Sparkles, Building2, Wallet, Briefcase, CalendarDays } from "./icons";
import type { Role } from "@/core/roles";

export function AppHeader({name,role,guest=false}:{name:string;role:Role;guest?:boolean}){const [open,setOpen]=useState(false);const path=usePathname();const first=name.trim().split(/\s+/)[0]||"Perfil";return <><header className="market-header"><button className="market-head-button" aria-label="Abrir menú" onClick={()=>setOpen(true)}><ListChecks size={21}/></button><Link href="/explore" className="market-wordmark"><Mark size={25}/><span>ALL LIVING</span></Link><Link href={guest?"/sign-in":"/profile"} className="market-profile"><span className="market-avatar"><UserRound size={18}/></span><span className="hidden sm:block"><strong>{guest?"Entrar":first}</strong><small>{guest?"Tu cuenta":role==="owner"?"Hospedar":role==="provider"?"Ofrecer":role==="operator"?"Operar":"Viajar"}</small></span></Link></header>{open?<><button className="market-menu-backdrop" aria-label="Cerrar menú" onClick={()=>setOpen(false)}/><aside className="market-menu"><div className="market-menu-top"><Mark size={30}/><button onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></div><p className="market-menu-kicker">DESCUBRE</p><nav><Link href="/explore" onClick={()=>setOpen(false)} className={path.startsWith("/explore")?"is-active":""}><Compass size={21}/><span>Explorar</span></Link><Link href="/flights" onClick={()=>setOpen(false)} className={path.startsWith("/flights")?"is-active":""}><Plane size={21}/><span>Vuelos</span></Link><Link href="/services" onClick={()=>setOpen(false)} className={path.startsWith("/services")?"is-active":""}><Sparkles size={21}/><span>Experiencias y servicios</span></Link><Link href="/properties" onClick={()=>setOpen(false)} className={path.startsWith("/properties")?"is-active":""}><Building2 size={21}/><span>Estancias</span></Link></nav>{!guest?<><p className="market-menu-kicker">TU ALL LIVING</p><nav><Link href="/stays" onClick={()=>setOpen(false)}><CalendarDays size={21}/><span>Mis viajes</span></Link><Link href="/profile/mode" onClick={()=>setOpen(false)}><Briefcase size={21}/><span>Cambiar modo</span></Link><Link href="/income" onClick={()=>setOpen(false)}><Wallet size={21}/><span>Ingresos</span></Link></nav></>:null}</aside></>:null}</>}
