import type { Metadata } from "next";
import { LegalShell } from "@/ui/site-chrome";
export const metadata: Metadata = { title: "Términos de Uso y Aviso Legal", alternates: { canonical: "/terminos" } };
export default function TermsPage() {
  return <LegalShell><p className="legal-eyebrow">ANTES DE VIVIR EL MOMENTO</p><h1>Términos de Uso<br />y Aviso Legal</h1><p className="legal-date">Última actualización: 16 de septiembre de 2026</p>
    <div className="legal-notice">ALL LIVING Eventos es un servicio independiente de descubrimiento. La compra de tus boletos se completa directamente en Ticketmaster.</div>
    <h2>1. Quién opera este sitio</h2><p>events.alliving.live es operado por Colectivo Mass S.A. de C.V. Puedes contactarnos en <a href="mailto:luisdelator@vmomentums.info">luisdelator@vmomentums.info</a>. El acceso a la cartelera y la búsqueda son gratuitos y no requieren registro.</p>
    <h2>2. Alcance del servicio y relación con Ticketmaster</h2><p>Consultamos información de eventos mediante Ticketmaster Discovery API. ALL LIVING Eventos no es Ticketmaster, no representa a Ticketmaster ni actúa como su agente, organizador o vendedor de boletos. No existe afiliación corporativa ni una relación distinta del acceso de descubrimiento autorizado y, cuando corresponda, la relación de afiliados expresamente aprobada. El uso de la API no implica una recomendación o respaldo de Ticketmaster hacia este sitio.</p><p>Esta versión enlaza a las fichas oficiales sin añadir seguimiento de afiliados. No promete descuentos exclusivos, acceso preferente ni convenios de venta directa.</p>
    <h2>3. Información de los eventos</h2><p>En la cartelera real, los nombres, fechas, recintos, imágenes, precios y disponibilidad provienen de Ticketmaster y pueden cambiar o dejar de estar disponibles. Una tarifa “Desde” es una referencia publicada, no una cotización ni una reserva; el importe final, cargos, categorías de acceso y condiciones se confirman en Ticketmaster antes del pago. Si Ticketmaster no informa un precio, te indicamos que lo consultes en su sitio.</p><p>La consulta tiene una actualización temporal para respetar los límites de la API. Un resultado no garantiza inventario. Una plaza sin eventos publicados se muestra como vacía; una falla de conexión se identifica por separado. Las fotografías generales de portada y ciudades son ambientales y no anuncian eventos concretos.</p><p>La experiencia marcada “DEMO” es independiente de la cartelera real. Sus artistas, fechas, recintos, imágenes ambientales, zonas y precios son ejemplos para probar la interfaz. No anuncia presentaciones, no confirma contrataciones de artistas y no ofrece inventario real. Los nombres de artistas y enlaces de Spotify identifican referencias musicales; no implican patrocinio ni respaldo.</p>
    <h2>4. Compra, pagos y atención de boletos</h2><p>Al abrir “Ver boletos” accedes a Ticketmaster.com o a su dominio oficial para México. Ahí se realiza el 100% de la compra, sujeta a sus <a href="https://www.ticketmaster.com.mx/h/terms.html" target="_blank" rel="noopener noreferrer">términos y condiciones</a> y <a href="https://privacy.ticketmaster.com.mx/es/privacy-policy" target="_blank" rel="noopener noreferrer">Aviso de Privacidad</a>. ALL LIVING Eventos no procesa pagos, no recibe datos financieros, no reserva inventario y no emite boletos.</p><p>Las consultas sobre compras, cargos, entrega, cambios, cancelaciones o reembolsos deben dirigirse a Ticketmaster y al organizador conforme a sus condiciones. Esto no limita los derechos que te reconozca la legislación aplicable.</p>
    <h2>5. Uso permitido y propiedad intelectual</h2><p>Usa el sitio para descubrir eventos y acceder a sus fichas oficiales. No intentes alterar el servicio, extraer credenciales, eludir límites o realizar consultas automatizadas abusivas. Las marcas, nombres e imágenes de Ticketmaster, los artistas y los organizadores pertenecen a sus titulares; su aparición identifica la fuente y el evento, sin transferir derechos.</p><p>Si eres titular de contenido y deseas reportar un uso incorrecto o solicitar su retiro, escribe a nuestro contacto indicando la ficha y el motivo para que podamos atenderlo.</p>
    <h2>6. Un espacio dedicado a eventos y una demo claramente identificada</h2><p>Este subdominio se dedica exclusivamente a eventos y al enlace a sus boletos oficiales. No ofrece paquetes, precios combinados ni un carrito compartido con otros servicios.</p><p>El acceso, perfil, carrito, pago y comprobantes marcados como demo funcionan únicamente en el navegador, sin autenticación real, cobros, reservas de fechas, apartados de inventario ni emisión de boletos. Una confirmación simulada no es un comprobante fiscal, boleto ni derecho de acceso. Los archivos de calendario descargables también son de demostración y no confirman una presentación. Los datos locales pueden borrarse desde Ajustes.</p><p>Los eventos reales no se agregan al carrito de demostración. Para comprar un boleto real debes continuar en Ticketmaster y aceptar sus condiciones. Spotify y OpenStreetMap se utilizan bajo sus propias políticas; el mapa de la demo muestra ubicaciones ilustrativas.</p>
    <h2>7. Disponibilidad y cambios</h2><p>Podemos realizar mantenimiento, corregir información o actualizar estos términos. Las interrupciones y la disponibilidad de servicios externos pueden afectar las consultas. Publicaremos los cambios en esta página. Ninguna disposición excluye responsabilidades ni derechos que no puedan limitarse legalmente.</p>
  </LegalShell>;
}
