"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDots, Minus, Plus, ShieldCheck, ShoppingBag, Trash } from "@phosphor-icons/react";
import { DEMO_EVENTS, currency, eventDate } from "./catalog";
import { cartTotal, unitPrice } from "./demo-model";
import { Empty, PageTitle } from "./primitives";
import { useExperience } from "./provider";
import s from "./experience.module.css";
export function CartPage() {
  const { state, setState, notify } = useExperience(); const count = state.cart.reduce((sum, item) => sum + item.quantity, 0);
  function update(key: string, quantity: number) { setState(old => ({ ...old, cart: old.cart.map(item => item.key === key ? { ...item, quantity: Math.max(1, Math.min(6, quantity)) } : item) })); }
  return <><PageTitle eyebrow="EL “VAMOS” YA ESTÁ TOMANDO FORMA" title="Tu próximo gran plan."><Link href="/app" className={s.secondary}>Seguir explorando <ArrowUpRight size={17} /></Link></PageTitle><p className={s.demoNotice}><ShoppingBag size={17} />Carrito de demostración. No aparta fechas, zonas ni inventario real.</p>{state.cart.length ? <div className={s.cartLayout}><div className={s.cartItems}>{state.cart.map(item => { const event = DEMO_EVENTS.find(e => e.id === item.eventId)!; return <article className={s.cartItem} key={item.key}><Link href={`/app/evento/${event.id}`} className={s.cartImage}><Image src={event.image} alt="" fill sizes="160px" /></Link><div className={s.cartItemBody}><span className={s.eyebrow}>DEMO · {event.cityLabel}</span><Link href={`/app/evento/${event.id}`}><h2>{event.title}</h2></Link><p><CalendarDots size={15} />{eventDate(item.date)} · {event.time} h</p><small>{item.zone} · {event.venue}</small><div className={s.cartItemActions}><div className={s.stepper}><button aria-label={`Quitar un boleto de ${event.title}`} disabled={item.quantity <= 1} onClick={() => update(item.key, item.quantity - 1)}><Minus size={14} /></button><output>{item.quantity}</output><button aria-label={`Agregar un boleto de ${event.title}`} disabled={item.quantity >= 6} onClick={() => update(item.key, item.quantity + 1)}><Plus size={14} /></button></div><button className={s.textButton} onClick={() => { setState(old => ({ ...old, cart: old.cart.filter(i => i.key !== item.key) })); notify("Evento retirado del carrito demo"); }} aria-label={`Eliminar ${event.title} del carrito`}><Trash size={17} />Eliminar</button></div></div><div className={s.cartPrice}><strong>{currency(unitPrice(item) * item.quantity)}</strong><small>MXN · de muestra</small><span>{currency(unitPrice(item))} por boleto</span></div></article>; })}<Link href="/app" className={s.addMore}><Plus size={20} />Siempre cabe otro buen plan <ArrowUpRight size={18} /></Link></div><aside className={s.orderSummary}><span className={s.eyebrow}>TODO LISTO PARA LA SIGUIENTE PARTE</span><h2>Resumen de tu plan</h2><div><span>{count} boletos de ejemplo</span><strong>{currency(cartTotal(state.cart))}</strong></div><div><span>Cargos de muestra</span><span>$0</span></div><div className={s.summaryTotal}><span>Total de muestra</span><strong>{currency(cartTotal(state.cart))}<small> MXN</small></strong></div><Link href="/app/pago" className={s.primary}>Continuar a la simulación <ArrowRight size={19} /></Link><p className={s.bookingDisclaimer}><ShieldCheck size={19} />Ningún cargo se realizará. Las compras reales se completan en Ticketmaster.</p></aside></div> : <Empty title="Aquí empieza ese “ya tenemos plan”." text="Elige un evento de muestra, una fecha y tu lugar. Después podrás recorrer el pago simulado de principio a fin." href="/app" action="Descubrir mi próximo plan" />}</>;
}
