import type { TicketmasterEvent, EventsPlace } from "@/lib/ticketmaster";

export type ExperienceEvent = {
  id: string; source: "demo" | "ticketmaster"; title: string; subtitle: string;
  artist: string; spotifyId?: string; city: EventsPlace; cityLabel: string;
  venue: string; date: string; dates: string[]; time: string; category: string; genre: string;
  price: number | null; currency: string; image: string; color: string;
  coordinates: [number, number] | null; ticketUrl?: string; description: string;
};
export const CITIES = [
  { id: "all", label: "Todas las ciudades", short: "Todo el Caribe", image: "/events/live-stage.webp", coordinates: [20.7, -87.1] },
  { id: "cancun", label: "Cancún", short: "Cancún", image: "/demo/palms.webp", coordinates: [21.1617, -86.8517] },
  { id: "playa-del-carmen", label: "Playa del Carmen", short: "Playa", image: "/demo/sunset.webp", coordinates: [20.6303, -87.0742] },
  { id: "tulum", label: "Tulum", short: "Tulum", image: "/demo/tulum-sea.webp", coordinates: [20.2114, -87.4656] },
] as const;
export const DEMO_EVENTS: ExperienceEvent[] = [
  { id: "demo-rufus", source: "demo", title: "RÜFÜS DU SOL", subtitle: "Una noche. Todos los sentidos.", artist: "RÜFÜS DU SOL", spotifyId: "5Pb27ujIyYb33zBqVysBkj", city: "tulum", cityLabel: "Tulum", venue: "Escenario Selva · muestra", date: "2026-11-14", dates: ["2026-11-14", "2026-11-15"], time: "20:00", category: "Music", genre: "Electrónica", price: 1850, currency: "MXN", image: "/events/demo/electronic.webp", color: "#9069df", coordinates: [20.215, -87.458], description: "Luces que te envuelven. Un bajo que se siente. Una noche que empieza con tu canción favorita y se queda contigo. Explora cómo sería elegir fecha, zona y compañía en esta experiencia de demostración." },
  { id: "demo-jungle", source: "demo", title: "Jungle", subtitle: "El cuerpo pide pista.", artist: "Jungle", spotifyId: "59oA5WbbQvomJz2BuRG071", city: "cancun", cityLabel: "Cancún", venue: "Foro Caribe · muestra", date: "2026-10-24", dates: ["2026-10-24", "2026-10-25"], time: "21:00", category: "Music", genre: "Funk & soul", price: 990, currency: "MXN", image: "/events/demo/live.webp", color: "#d9a157", coordinates: [21.166, -86.839], description: "Ritmo, luces cálidas y ese momento en el que toda la pista canta lo mismo. Una ficha de muestra para descubrir al artista, escuchar su música y armar tu plan." },
  { id: "demo-mon", source: "demo", title: "Mon Laferte", subtitle: "Hay canciones que se quedan.", artist: "Mon Laferte", spotifyId: "4boI7bJtmB1L3b1cuL75Zr", city: "playa-del-carmen", cityLabel: "Playa del Carmen", venue: "Teatro Riviera · muestra", date: "2026-11-07", dates: ["2026-11-07", "2026-11-08"], time: "20:30", category: "Music", genre: "Alternativo", price: 850, currency: "MXN", image: "/events/demo/spotlight.webp", color: "#cf717d", coordinates: [20.634, -87.067], description: "Una voz, mil emociones y una noche para cantar sin mirar el reloj. Esta ficha ilustra la experiencia de descubrimiento y selección de boletos; no anuncia una presentación del artista." },
  { id: "demo-court", source: "demo", title: "Caribe Basketball Night", subtitle: "Tu lugar está junto a la cancha.", artist: "Deporte en el Caribe", city: "cancun", cityLabel: "Cancún", venue: "Arena del Mar · muestra", date: "2026-10-18", dates: ["2026-10-18", "2026-10-19"], time: "18:00", category: "Sports", genre: "Básquetbol", price: 480, currency: "MXN", image: "/events/demo/court.webp", color: "#d98b53", coordinates: [21.151, -86.844], description: "La energía de la tribuna, una jugada que cambia todo y una tarde para compartir. Evento deportivo ficticio para probar fechas, zonas y la compra de demostración." },
  { id: "demo-luz", source: "demo", title: "Luz entre la selva", subtitle: "Déjate sorprender por la escena.", artist: "Compañía de muestra", city: "tulum", cityLabel: "Tulum", venue: "Escena Tulum · muestra", date: "2026-10-31", dates: ["2026-10-31", "2026-11-01"], time: "19:30", category: "Arts & Theatre", genre: "Arte y escena", price: 620, currency: "MXN", image: "/events/live-stage.webp", color: "#6397bf", coordinates: [20.205, -87.469], description: "Movimiento, luz y una historia que se vive desde todos los ángulos. Espectáculo ficticio creado exclusivamente para recorrer esta demo." },
  { id: "demo-riviera", source: "demo", title: "Riviera Afterglow", subtitle: "Del atardecer a tu mejor noche.", artist: "Selección de muestra", spotifyId: "59oA5WbbQvomJz2BuRG071", city: "playa-del-carmen", cityLabel: "Playa del Carmen", venue: "Terraza Riviera · muestra", date: "2026-11-21", dates: ["2026-11-21", "2026-11-22"], time: "18:30", category: "Music", genre: "Festival", price: 1250, currency: "MXN", image: "/events/demo/festival.webp", color: "#b98ccb", coordinates: [20.625, -87.065], description: "Un atardecer que se convierte en festival. Este evento ficticio permite probar el mapa, guardar favoritos y preparar un plan de muestra. La música es una referencia ambiental." },
];
export const DEMO_NOTICE = "Demo del producto: artistas, fechas, recintos y precios de ejemplo. No anuncia presentaciones ni reserva boletos.";
export function currency(value: number, code = "MXN") { return new Intl.NumberFormat("es-MX", { style: "currency", currency: code, maximumFractionDigits: 0 }).format(value); }
export function eventDate(value: string, long = false) { return new Intl.DateTimeFormat("es-MX", { day: "numeric", month: long ? "long" : "short", ...(long ? { weekday: "long" as const } : {}), timeZone: "America/Cancun" }).format(new Date(`${value}T12:00:00-05:00`)).replaceAll(".", ""); }
export function fromTicketmaster(event: TicketmasterEvent, city: EventsPlace): ExperienceEvent {
  return { id: event.id, source: "ticketmaster", title: event.title, subtitle: "Publicado en Ticketmaster", artist: event.artist ?? event.title, spotifyId: event.spotifyId ?? undefined, city, cityLabel: CITIES.find(c => c.id === city)?.label ?? event.city, venue: event.venue, date: event.date, dates: [event.date], time: event.time?.slice(0, 5) ?? "Por confirmar", category: event.segment ?? "Other", genre: event.segment === "Music" ? "Música en vivo" : event.segment === "Sports" ? "Deportes" : "Espectáculo", price: event.price?.min ?? null, currency: event.price?.currency ?? "MXN", image: event.imageUrl ?? "/events/live-stage.webp", color: "#168c9d", coordinates: event.coordinates ?? null, ticketUrl: event.ticketUrl, description: "Consulta la información publicada por Ticketmaster y continúa en la ficha oficial para confirmar disponibilidad, zonas, cargos y condiciones antes de comprar." };
}
