"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CalendarDots, Check, Clock, MapPin, Minus, Plus, ShareNetwork, ShoppingBag, Sparkle, Ticket, ShieldCheck } from "@phosphor-icons/react";
import { DEMO_EVENTS, DEMO_NOTICE, currency, eventDate, type ExperienceEvent } from "./catalog";
import { ZONES, addCartItem, unitPrice, type CartItem } from "./demo-model";
import { Empty, FavoriteButton, SpotifyPlayer } from "./primitives";
import { useExperience } from "./provider";
import { useLiveCatalog } from "./use-catalog";
import s from "./experience.module.css";

export function EventDetail() {
  const { id } = useParams<{ id: string }>(); const { liveEvents } = useExperience();
  const event = DEMO_EVENTS.find(event => event.id === id) ?? liveEvents.find(event => event.id === id);
  const live = useLiveCatalog(!event && !id.startsWith("demo-"));
  const found = event ?? live.events.find(event => event.id === id);
  if (found) return <DetailBody event={found} key={found.id} />;
  if (live.loading) return <div className={s.skeleton} role="status">Cargando evento…</div>;
  return <Empty title={live.error ? "La ficha no pudo cargarse." : "Este plan ya no está disponible."} text={live.error || "Vuelve a la cartelera para encontrar los eventos publicados actualmente."} href="/app" action="Explorar eventos" />;
}
function DetailBody({ event }: { event: ExperienceEvent }) {
  const { setState, notify } = useExperience(); const demo = event.source === "demo";
  const [date, setDate] = useState(event.date); const [zone, setZone] = useState<CartItem["zone"]>("General"); const [quantity, setQuantity] = useState(2); const [added, setAdded] = useState(false);
  const item: CartItem = { key: `${event.id}:${date}:${zone}`, eventId: event.id, date, zone, quantity };
  async function share() { try { await navigator.clipboard.writeText(window.location.href); notify("Enlace copiado para compartir el plan"); } catch { notify("Copia el enlace desde la barra del navegador para compartirlo"); } }
  return <><div className={s.backRow}><Link href="/app"><ArrowLeft size={18} />Volver a descubrir</Link><button onClick={share} className={s.textButton}><ShareNetwork size={18} />Compartir</button></div><section className={s.detailHero}><Image src={event.image} alt={demo ? "Fotografía ambiental para una ficha de demostración" : event.title} fill priority sizes="100vw" unoptimized={!demo} /><div className={s.detailHeroTop}><span className={s.glassPill}>{demo ? "EVENTO DE DEMOSTRACIÓN" : "PUBLICADO POR TICKETMASTER"}</span><FavoriteButton event={event} /></div><div className={s.detailHeroCopy}><p>{event.genre} · {event.cityLabel}</p><h1>{event.title}</h1><span>{event.subtitle}</span></div></section>
  {demo && <p className={s.demoNotice}><Sparkle size={16} />{DEMO_NOTICE}</p>}
  <div className={s.detailColumns}><div className={s.detailContent}><div className={s.eventFacts}><span><CalendarDots size={23} weight="duotone" /><strong>{eventDate(event.date, true)}<small>{demo ? "2026 · fecha de muestra" : event.date.slice(0, 4)}</small></strong></span><span><Clock size={23} weight="duotone" /><strong>{event.time} h<small>Hora local del recinto</small></strong></span><span><MapPin size={23} weight="duotone" /><strong>{event.cityLabel}<small>{event.venue}</small></strong></span></div><section className={s.detailSection}><p className={s.eyebrow}>HAY NOCHES QUE LO CAMBIAN TODO</p><h2>Esto se siente <em>en vivo.</em></h2><p>{event.description}</p><div className={s.tagRow}><span>{event.genre}</span><span>{event.cityLabel}</span><span>{demo ? "Experiencia de muestra" : "Información oficial"}</span></div></section><section className={s.detailSection}><h2>Empieza con <em>una canción.</em></h2><SpotifyPlayer event={event} /></section><section className={s.venuePanel}><MapPin size={29} weight="duotone" /><div><span className={s.eyebrow}>EL PUNTO DE ENCUENTRO</span><h3>{event.venue}</h3><p>{event.cityLabel} · Quintana Roo</p><small>{demo ? "Ubicación ilustrativa. No corresponde a un recinto confirmado." : event.coordinates ? "Ubicación publicada por Ticketmaster." : "Este evento no tiene coordenadas publicadas."}</small></div><Link href="/app/mapa" className={s.secondary}><ArrowUpRight size={20} />Ver mapa</Link></section></div>
  <aside className={s.bookingCard}><span className={s.eyebrow}>{demo ? "ARMA TU PLAN · DEMO" : "TU NOCHE EMPIEZA AQUÍ"}</span><h2>{demo ? "Elige cómo vivirlo." : "Tus boletos, en Ticketmaster."}</h2>{demo ? <><div className={s.bookingDates}><label className={s.field}>1. Elige tu fecha<select value={date} onChange={e => { setDate(e.target.value); setAdded(false); }}>{event.dates.map(date => <option key={date} value={date}>{eventDate(date, true)} · {event.time} h</option>)}</select></label></div><fieldset className={s.zoneChoices}><legend>2. Encuentra tu lugar</legend>{ZONES.map(z => <label key={z.id} data-active={zone === z.id}><input type="radio" name="zone" checked={zone === z.id} onChange={() => { setZone(z.id); setAdded(false); }} /><span><strong>{z.id}</strong><small>{z.description}</small></span><b>{currency(Math.round((event.price ?? 0) * z.multiplier))}</b></label>)}</fieldset><div className={s.quantityRow}><span><strong>3. ¿Cuántos van?</strong><small>Hasta 6 por selección de muestra</small></span><div className={s.stepper}><button aria-label="Quitar un boleto" disabled={quantity <= 1} onClick={() => { setQuantity(q => q - 1); setAdded(false); }}><Minus size={15} /></button><output aria-label="Cantidad de boletos">{quantity}</output><button aria-label="Agregar un boleto" disabled={quantity >= 6} onClick={() => { setQuantity(q => q + 1); setAdded(false); }}><Plus size={15} /></button></div></div><div className={s.bookingTotal}><span>Total de muestra<small>{quantity} boletos · {zone}</small></span><strong>{currency(unitPrice(item) * quantity)}<small> MXN</small></strong></div><button className={s.primary} disabled={added} onClick={() => { setState(old => ({ ...old, cart: addCartItem(old.cart, item) })); setAdded(true); notify("Agregado al carrito demo. No se reservó inventario real."); }}>{added ? <Check size={20} /> : <ShoppingBag size={20} />}{added ? "Agregado a tu plan" : "Agregar al carrito demo"}</button>{added && <Link className={s.secondary} href="/app/carrito">Continuar al carrito <ArrowUpRight size={18} /></Link>}<p className={s.bookingDisclaimer}><ShieldCheck size={18} />Sin cobros. Sin reserva de boletos. Todos los importes y zonas son de ejemplo.</p></> : <><p className={s.livePrice}>{event.price === null ? "Consulta el precio oficial" : <>Desde <strong>{currency(event.price, event.currency)}</strong> {event.currency}</>}</p><p className={s.bodyCopy}>Confirma la fecha, las zonas disponibles, los cargos y el precio final en la ficha oficial.</p><a className={s.primary} href={event.ticketUrl} target="_blank" rel="noopener noreferrer">Ver boletos en Ticketmaster <ArrowUpRight size={19} /></a><p className={s.bookingDisclaimer}><Ticket size={18} />La compra se completa en Ticketmaster. Este sitio no cobra ni reserva boletos reales.</p></>}</aside></div></>;
}
