"use client";
import { useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDots, MagnifyingGlass, MapPin, MapTrifold, MusicNotes, SlidersHorizontal, Sparkle, SpotifyLogo, Basketball, MaskHappy, SquaresFour, X } from "@phosphor-icons/react";
import { CITIES, DEMO_EVENTS, DEMO_NOTICE, currency, eventDate } from "./catalog";
import { useExperience } from "./provider";
import { useEventsAccount } from "./account-context";
import { Empty, EventTile, FavoriteButton, Modal } from "./primitives";
import { useLiveCatalog } from "./use-catalog";
import s from "./experience.module.css";
const categories = [{ id: "all", label: "Para ti", icon: SquaresFour }, { id: "Music", label: "Música", icon: MusicNotes }, { id: "Sports", label: "Deportes", icon: Basketball }, { id: "Arts & Theatre", label: "Arte y escena", icon: MaskHappy }];
export function Discovery() {
  const account = useEventsAccount();
  const { state } = useExperience();
  const [city, setCity] = useState("all"); const [category, setCategory] = useState("all");
  const [q, setQ] = useState(""); const [keyword, setKeyword] = useState(""); const [date, setDate] = useState("");
  const [maxPrice, setMaxPrice] = useState(4000); const [sort, setSort] = useState("recommended"); const [filters, setFilters] = useState(false);
  const demo = state.mode === "demo";
  const query = new URLSearchParams({ city, category, q: keyword, date }).toString();
  const live = useLiveCatalog(!demo, query);
  const shown = useMemo(() => {
    const events = (demo ? DEMO_EVENTS : live.events).filter(event => (!demo || ((city === "all" || event.city === city) && (category === "all" || event.category === category) && (!date || event.dates.includes(date)) && `${event.title} ${event.genre} ${event.venue}`.toLocaleLowerCase("es").includes(keyword.toLocaleLowerCase("es")))) && (maxPrice === 4000 || event.price !== null && event.currency === "MXN" && event.price <= maxPrice));
    return sort === "price" ? [...events].sort((a, b) => (a.price ?? Infinity) - (b.price ?? Infinity)) : sort === "date" ? [...events].sort((a, b) => a.date.localeCompare(b.date)) : events;
  }, [demo, live.events, city, category, date, keyword, maxPrice, sort]);
  const featured = DEMO_EVENTS[0];
  const filtered = city !== "all" || category !== "all" || date || keyword || maxPrice < 4000;
  function reset() { setCity("all"); setCategory("all"); setDate(""); setQ(""); setKeyword(""); setMaxPrice(4000); }
  return <>
    <div className={s.welcome}><div><p className={s.eyebrow}>TU PRÓXIMO “TENÍAS QUE ESTAR AHÍ”</p><h1>{account.signedIn ? `Hola, ${account.name.split(" ")[0]}. ` : state.signedIn ? `Hola, ${state.profile.name.split(" ")[0]}. ` : "Sal de la rutina. "}<em>Sal a vivir.</em></h1></div><span className={s.locationPill}><MapPin size={17} weight="fill" />Quintana Roo <span>MX</span></span></div>
    <section className={s.discoveryHero} aria-label="Inspírate para tu próximo plan"><article className={s.heroEvent}><Image src={demo ? featured.image : "/events/live-stage.webp"} alt="Ambiente de música en vivo" fill priority sizes="(max-width: 780px) 100vw, 70vw" /><div className={s.heroEventTop}><span className={s.glassPill}><Sparkle size={13} weight="fill" />{demo ? "DESTACADO DE LA DEMO" : "LA VIDA SUENA MEJOR EN VIVO"}</span>{demo && <FavoriteButton event={featured} />}</div><div className={s.heroEventCopy}><p>{demo ? "ELECTRÓNICA · TULUM" : "CONCIERTOS · DEPORTES · ESPECTÁCULOS"}</p><h2>{demo ? <>RÜFÜS<br /><em>DU SOL.</em></> : <>Tu ciudad.<br /><em>En primera fila.</em></>}</h2><span>{demo ? "Una noche. Todos los sentidos." : "Encuentra un buen motivo para estar ahí."}</span><div className={s.heroEventBottom}>{demo ? <><div><CalendarDots size={18} /><span>{eventDate(featured.date)}<small>Fecha de muestra</small></span></div><Link href={`/app/evento/${featured.id}`} className={s.lightButton}>Explorar evento <ArrowUpRight size={18} /></Link></> : <a href="#descubre" className={s.lightButton}>Explorar la cartelera <ArrowRight size={18} /></a>}</div></div><div className={s.heroDots} aria-hidden><i /><i /><i /></div></article>
    <aside className={s.heroSide}><Link href="/app/musica" className={s.previaTeaser}><div><span className={s.eyebrow}>ANTES DE ESTAR AHÍ</span><SpotifyLogo size={29} weight="fill" /></div><h2>La previa<br /><em>también se vive.</em></h2><div className={s.record} aria-hidden><div>AL<br /><span>LIVE SESSIONS</span></div></div><footer><span>Encuentra tu próximo repeat<small>Artistas de la demo · Spotify</small></span><span className={s.roundArrow}><ArrowUpRight size={22} /></span></footer></Link><Link href="/app/mapa" className={s.mapTeaser}><MapTrifold size={33} weight="duotone" /><div><strong>El Caribe, en modo vivo.</strong><span>Encuentra tu plan en el mapa</span></div><ArrowUpRight size={20} /></Link></aside></section>
    <section className={s.citySection} aria-label="Explorar por ciudad"><div><p className={s.eyebrow}>ELIGE TU ESCENARIO</p><h2>¿Dónde nos vemos?</h2></div><div className={s.cityChoices}>{CITIES.map(c => <button key={c.id} onClick={() => setCity(c.id)} aria-pressed={city === c.id}><span><Image src={c.image} alt="" width={54} height={54} /></span><span>{c.short}<small>{c.id === "all" ? "Sin límites al plan" : "Descubre la ciudad"}</small></span>{city === c.id && <i />}</button>)}</div></section>
    <section id="descubre" className={s.discoverSection}><div className={s.sectionTitle}><div><p className={s.eyebrow}>HAZLE ESPACIO EN TU AGENDA</p><h2>Esto te va a <em>mover.</em></h2></div><Link href="/app/mapa" className={s.secondary}><MapTrifold size={18} />Ver en mapa</Link></div><div className={s.categoryTabs} role="group" aria-label="Tipo de evento">{categories.map(c => <button key={c.id} aria-pressed={category === c.id} onClick={() => setCategory(c.id)}><c.icon size={19} weight={category === c.id ? "fill" : "regular"} />{c.label}</button>)}</div>
    <form className={s.searchBar} onSubmit={e => { e.preventDefault(); setKeyword(q.trim()); }}><label className={s.searchInput}><MagnifyingGlass size={20} /><input aria-label="Buscar artista, evento o recinto" placeholder="Artista, evento o ese plan que traes en mente…" value={q} maxLength={80} onChange={e => setQ(e.target.value)} /></label><label className={s.dateInput}><CalendarDots size={19} /><input aria-label="Fecha del evento" type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button type="button" className={s.filterButton} onClick={() => setFilters(true)}><SlidersHorizontal size={19} /><span>Filtros</span>{maxPrice < 4000 && <i />}</button><button type="submit" className={s.primary}>Buscar<ArrowRight size={17} /></button></form>
    <div className={s.resultsInfo}><p role="status">{!demo && live.loading ? "Consultando Ticketmaster…" : `${shown.length} ${shown.length === 1 ? "plan" : "planes"} ${demo ? "para explorar en la demo" : "publicados en Ticketmaster"}`}{filtered && <button className={s.textButton} onClick={reset}>Limpiar filtros <X size={13} /></button>}</p><label>Ordenar:<select aria-label="Ordenar eventos" value={sort} onChange={e => setSort(e.target.value)}><option value="recommended">Destacados</option><option value="date">Próxima fecha</option><option value="price">Menor precio</option></select></label></div>
    {demo && <p className={s.demoNotice}><Sparkle size={15} />{DEMO_NOTICE}</p>}
    {!demo && live.error && <div className={s.errorNotice} role="alert"><p>{live.error}</p><button onClick={live.retry} className={s.secondary}>Volver a intentar</button></div>}
    {!demo && live.loading ? <div className={s.eventGrid} aria-label="Cargando cartelera">{[1, 2, 3].map(i => <div key={i} className={s.skeleton} />)}</div> : shown.length ? <div className={s.eventGrid}>{shown.map(event => <EventTile key={event.id} event={event} />)}</div> : !live.error || demo ? <Empty title={demo || filtered ? "El próximo plan sigue ahí." : "La cartelera está por encenderse."} text={demo || filtered ? "No hay coincidencias con estos filtros. Prueba otra fecha, ciudad o artista." : "Ticketmaster no tiene eventos publicados por ahora para estas plazas. Vuelve pronto para descubrir nuevas fechas."} /> : null}
    {!demo && <p className={s.microcopy}>Precios y disponibilidad publicados por Ticketmaster, sujetos a cambios. La compra se completa en su sitio oficial.</p>}</section>
    <section className={s.bottomBanner}><div><span className={s.eyebrow}>LOS MEJORES PLANES EMPIEZAN CON UN “VAMOS”</span><h2>Haz que tu próxima historia<br />se cuente <em>en vivo.</em></h2></div><Link className={s.primary} href="/app/guardados">Arma tu lista <ArrowUpRight size={20} /></Link><Sparkle className={s.bannerSpark} size={115} weight="thin" aria-hidden /></section>
    <Modal open={filters} close={() => setFilters(false)} title="Encuentra tu tipo de plan"><div className={s.filterFields}><label className={s.field}>Ciudad<select value={city} onChange={e => setCity(e.target.value)}>{CITIES.map(c => <option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label className={s.field}>Tipo de evento<select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label className={s.field}>Presupuesto por boleto <strong>{maxPrice === 4000 ? "Cualquier precio" : `Hasta ${currency(maxPrice)} MXN`}</strong><input type="range" min={400} max={4000} step={100} value={maxPrice} onChange={e => setMaxPrice(Number(e.target.value))} /></label><p className={s.microcopy}>El filtro de presupuesto usa el precio base publicado en MXN. Los eventos sin precio se muestran al elegir “Cualquier precio”.</p><button className={s.primary} onClick={() => setFilters(false)}>Mostrar planes <ArrowRight size={18} /></button><button className={s.textButton} onClick={reset}>Restablecer filtros</button></div></Modal>
  </>;
}
