"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Compass, MapTrifold, ShoppingBag, Ticket, UserCircle, List, Bell, GearSix, SignOut, Heart, ArrowUpRight, DeviceMobile, MusicNotes } from "@phosphor-icons/react";
import { Mark } from "@/ui/mark";
import { useExperience } from "./provider";
import { useEventsAccount } from "./account-context";
import { Modal, Toast } from "./primitives";
import s from "./experience.module.css";
const nav = [{ href: "/app", label: "Descubrir", icon: Compass }, { href: "/app/mapa", label: "Mapa", icon: MapTrifold }, { href: "/app/carrito", label: "Carrito", icon: ShoppingBag }, { href: "/app/planes", label: "Mis planes", icon: Ticket }, { href: "/app/perfil", label: "Mi cuenta", icon: UserCircle }];
export function AppShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter(); const account = useEventsAccount(); const { state, setState, activity, ready, notify } = useExperience();
  const [menu, setMenu] = useState(false); const [notifications, setNotifications] = useState(false);
  async function leave() { setMenu(false); try { if (account.signedIn) await account.signOut(); else { setState(old => ({ ...old, signedIn: false })); router.push("/acceso"); } } catch { notify("No pudimos cerrar tu sesión. Intenta de nuevo."); } }
  const count = state.cart.reduce((sum, item) => sum + item.quantity, 0);
  return <div className={s.app} data-motion={state.settings.motion}>
    <a className={s.skip} href="#experience-content">Ir al contenido</a>
    <header className={s.appHeader}><button className={`${s.iconButton} ${s.mobileOnly}`} onClick={() => setMenu(true)} aria-label="Abrir menú"><List size={24} /></button><Link href="/app" className={s.logo} aria-label="ALL LIVING Eventos"><Mark size={35} /><span>ALL LIVING<small>EVENTOS</small></span></Link><nav className={s.desktopNav} aria-label="Navegación de eventos">{nav.filter(n => !["/app/carrito", "/app/perfil"].includes(n.href)).map(n => <Link href={n.href} key={n.href} aria-current={path === n.href ? "page" : undefined}>{n.label}</Link>)}<Link href="/app/musica" aria-current={path === "/app/musica" ? "page" : undefined}>La previa <span>♫</span></Link></nav><div className={s.headerActions}><Link href="/app/guardados" className={`${s.iconButton} ${s.desktopOnly}`} aria-label="Mis favoritos"><Heart size={22} /></Link><button className={s.iconButton} onClick={() => setNotifications(true)} aria-label="Ver actividad"><Bell size={22} />{activity.length > 0 && <i className={s.notificationDot} />}</button><Link href="/app/carrito" className={s.iconButton} aria-label={`Carrito, ${count} boletos de demostración`}><ShoppingBag size={22} />{count > 0 && <span className={s.badgeCount}>{count}</span>}</Link><Link href={account.signedIn || state.signedIn ? "/app/perfil" : "/acceso"} className={s.avatar} aria-label={account.signedIn || state.signedIn ? "Ver mi perfil" : "Entrar o crear cuenta"}>{account.signedIn ? account.initials : state.signedIn ? state.profile.avatar : <UserCircle size={23} />}</Link></div></header>
    <div className={s.modeStrip}><span><i />{state.mode === "demo" ? "ESTÁS EXPLORANDO LA DEMO" : "CARTELERA REAL · TICKETMASTER"}</span><Link href="/app" onClick={() => setState(old => ({ ...old, mode: old.mode === "demo" ? "live" : "demo" }))}>{state.mode === "demo" ? "Ver eventos reales" : "Explorar la demo"}<ArrowUpRight size={13} /></Link></div>
    <main id="experience-content" className={s.main}>{ready ? children : <div className={s.appLoading} role="status"><Mark size={55} /><p>Preparando tu próxima gran noche…</p></div>}</main>
    <footer className={s.appFooter}><span>ALL LIVING Eventos · Colectivo Mass S.A. de C.V.</span><nav><Link href="/privacidad">Privacidad</Link><Link href="/terminos">Términos</Link><Link href="/responsable">Contacto</Link><Link href="/eventos">Volver a la portada</Link></nav></footer>
    <nav className={s.tabbar} aria-label="Navegación móvil" data-vulcano-bottomnav>{nav.map((n, index) => <Link href={n.href} className={index === 2 ? s.centerTab : ""} aria-current={path === n.href ? "page" : undefined} key={n.href}><span><n.icon size={23} weight={path === n.href ? "fill" : "regular"} />{index === 2 && count > 0 && <b>{count}</b>}</span><small>{n.label}</small></Link>)}</nav>
    <Modal open={menu} close={() => setMenu(false)} title="Tu próximo gran plan" drawer><div className={s.drawerProfile}><span className={s.avatar}>{account.signedIn ? account.initials : state.profile.avatar}</span><div><strong>{account.signedIn ? account.name : state.signedIn ? state.profile.name : "Bienvenido a Eventos"}</strong><p>{account.signedIn ? "Tu cuenta de ALL LIVING Eventos" : "Un mundo por vivir · modo demo"}</p></div></div><nav className={s.drawerNav}>{[...nav, { href: "/app/guardados", label: "Mis favoritos", icon: Heart }, { href: "/app/musica", label: "La previa · música", icon: MusicNotes }, { href: "/app/ajustes", label: "Ajustes", icon: GearSix }].map(n => <Link key={n.href} href={n.href} onClick={() => setMenu(false)}><n.icon size={22} weight="duotone" />{n.label}<ArrowUpRight size={16} /></Link>)}<button onClick={() => { setMenu(false); window.dispatchEvent(new Event("events:install")); }}><DeviceMobile size={22} />Instalar la app<ArrowUpRight size={16} /></button></nav><button className={s.drawerLogout} onClick={leave}><SignOut size={20} />{account.signedIn ? "Cerrar sesión" : state.signedIn ? "Salir de la demo" : "Entrar o crear cuenta"}</button><p className={s.microcopy}>Descubrimiento libre. Las compras reales se completan en Ticketmaster.</p></Modal>
    <Modal open={notifications} close={() => setNotifications(false)} title="Tu actividad">{activity.length ? <ul className={s.activityList}>{activity.map((item, i) => <li key={`${i}-${item}`}><span><Bell size={18} /></span><div><p>{item}</p><small>En esta sesión de demostración</small></div></li>)}</ul> : <div className={s.empty}><Bell size={32} /><h2>Los buenos planes empiezan aquí.</h2><p>Cuando guardes eventos o prepares un plan, verás tu actividad aquí.</p></div>}</Modal><Toast />
  </div>;
}
