import type { Metadata } from "next";
import { LegalShell } from "@/ui/site-chrome";
export const metadata: Metadata = { title: "Aviso de Privacidad", alternates: { canonical: "/privacidad" } };
export default function PrivacyPage() {
  return <LegalShell><p className="legal-eyebrow">TU INFORMACIÓN, CON CLARIDAD</p><h1>Aviso de Privacidad</h1><p className="legal-date">Última actualización: 16 de septiembre de 2026</p>
    <div className="legal-notice">Puedes descubrir y buscar eventos sin crear una cuenta. Este sitio no cobra, no emite boletos y no recibe datos de tarjetas bancarias.</div>
    <h2>1. Responsable y contacto</h2><p>Colectivo Mass S.A. de C.V. es responsable de los datos tratados mediante events.alliving.live, denominado ALL LIVING Eventos. Su domicilio fiscal es Avenida Paseo de la Reforma 389, piso 19, colonia Juárez, alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, México.</p><p>Para consultas de privacidad, escribe a <a href="mailto:luisdelator@vmomentums.info">luisdelator@vmomentums.info</a>.</p>
    <h2>2. Qué información se trata</h2><p>Al visitar el sitio, la infraestructura de alojamiento de Vercel procesa datos técnicos como dirección IP, tipo de navegador, fecha, ruta solicitada y registros de errores para entregar las páginas, mantener su seguridad y diagnosticar fallas. Las direcciones de búsqueda pueden incluir el texto y los filtros que elegiste.</p><p>El buscador recibe palabras clave, ciudad, fecha y categoría. Estos criterios se envían desde nuestro servidor a la API de Ticketmaster para consultar la cartelera. No solicitamos tu nombre, correo, ubicación precisa, identificaciones ni información financiera para buscar. Evita escribir datos personales en el buscador.</p><p>Si nos escribes voluntariamente por correo, tratamos tu dirección, el contenido del mensaje y los datos que decidas adjuntar para responder y dar seguimiento a tu solicitud. No pedimos datos sensibles.</p>
    <p>La experiencia de demostración permite guardar en tu navegador un apodo, correo de muestra, ciudad, descripción, intereses, favoritos, preferencias, carrito y planes simulados. Puedes usar los datos de ejemplo precargados; evita introducir datos personales reales. Esta información se conserva en almacenamiento local del navegador, separado de la aplicación principal de All Living. No se envía a una base de datos, no se verifica tu identidad y no crea una cuenta real. Los métodos de pago de prueba están precargados: no hay campos para números de tarjeta, CVV, CLABE ni datos financieros.</p>
    <p>El registro es opcional y exclusivo de ALL LIVING Eventos. Si creas una cuenta, Clerk procesa tu correo, nombre o imagen si los proporcionas, datos de verificación, credenciales y sesiones, así como señales técnicas de seguridad. La contraseña se gestiona mediante Clerk; no se conserva en el almacenamiento local de la demo. No importamos usuarios, sesiones ni datos de la aplicación principal.</p>
    <h2>3. Finalidades</h2><p>Utilizamos la información para mostrar y buscar eventos, operar y proteger el sitio, resolver incidencias, crear y administrar la cuenta que solicites, verificar tu acceso, recuperar tu cuenta y atender consultas o solicitudes de privacidad. La información local de la demo sirve para conservar tu selección y personalizar el recorrido de muestra. No la utilizamos para crear perfiles publicitarios ni para enviar promociones.</p>
    <h2>4. Analítica, cookies y aplicación instalable</h2><p>Esta versión no incorpora Google Analytics, Vercel Web Analytics, píxeles publicitarios ni seguimiento de afiliados. Las pantallas de acceso y del interior utilizan Clerk para mantener la sesión y prevenir abuso mediante cookies e identificadores necesarios para la autenticación. No se utilizan para publicidad. El acceso demo sigue siendo una preferencia local y no autentica una identidad. La infraestructura de seguridad puede procesar señales técnicas para prevenir abuso.</p><p>Si tu navegador admite la aplicación instalable, un service worker conserva en tu dispositivo únicamente recursos básicos, íconos y una pantalla sin conexión. No almacena tu historial de búsquedas ni boletos reales. La demo utiliza, por separado, almacenamiento local para las preferencias y selecciones descritas arriba. Al iniciar sesión, esas preferencias se separan mediante el identificador de tu cuenta; no se sincronizan con otros dispositivos. Puedes exportar o borrar la demo desde Ajustes, o borrar todos los datos del sitio en la configuración del navegador. Desinstalar la PWA no siempre elimina el almacenamiento del navegador. Los resultados de Ticketmaster se conservan temporalmente en el servidor para reducir consultas repetidas: hasta 15 minutos para la cartelera y un minuto para búsquedas.</p>
    <h2>5. Proveedores y enlaces externos</h2><p>Vercel presta el alojamiento y puede procesar datos técnicos fuera de México según su infraestructura. Consulta su <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Aviso de Privacidad</a>. Ticketmaster recibe los criterios necesarios para responder a una búsqueda desde nuestro servidor; no le enviamos un perfil de usuario.</p><p>Al seleccionar “Ver boletos” sales de este sitio y entras a Ticketmaster. La compra y la entrega de información personal o financiera ocurren completamente en Ticketmaster.com o su dominio oficial para México, bajo su <a href="https://privacy.ticketmaster.com.mx/es/privacy-policy" target="_blank" rel="noopener noreferrer">propio Aviso de Privacidad</a>. Sus cookies, formularios, pagos y políticas son independientes. ALL LIVING Eventos no recibe los datos de esa compra.</p>
    <p>Clerk, Inc. presta el servicio de autenticación en una aplicación independiente de Eventos y procesa los datos necesarios para la cuenta conforme a nuestro encargo y sus <a href="https://clerk.com/legal/dpa" target="_blank" rel="noopener noreferrer">condiciones de tratamiento de datos</a>. Su infraestructura y subencargados pueden procesar información fuera de México. Consulta también su <a href="https://clerk.com/legal/privacy" target="_blank" rel="noopener noreferrer">Política de Privacidad</a>. No compartimos tu cuenta con Ticketmaster, Spotify ni la aplicación principal de All Living.</p>
    <p>Spotify se carga únicamente cuando eliges reproducir música. Su reproductor puede recibir tu dirección IP, navegador y datos de uso, y utilizar cookies conforme a su <a href="https://www.spotify.com/mx/legal/privacy-policy/" target="_blank" rel="noopener noreferrer">Política de Privacidad</a>. No recibimos credenciales de Spotify ni conectamos tu cuenta de música. La disponibilidad y duración de reproducción dependen de Spotify.</p><p>El mapa se carga cuando eliges “Abrir mapa”. OpenStreetMap Foundation recibe solicitudes de mapas que incluyen datos técnicos como IP, navegador y origen de la solicitud, conforme a su <a href="https://osmfoundation.org/wiki/Privacy_Policy" target="_blank" rel="noopener noreferrer">Política de Privacidad</a>. No solicitamos geolocalización precisa del dispositivo. Los pines de la demo son ilustrativos; los de la cartelera real usan las coordenadas publicadas por Ticketmaster.</p>
    <h2>6. Conservación y seguridad</h2><p>La información de las cuentas se conserva en la instancia propia de Clerk mientras la cuenta esté activa y durante los periodos de seguridad o conservación legal que correspondan. No utilizamos la base de datos de la aplicación principal. Los datos de la demo permanecen en tu navegador hasta que los borres, el navegador los elimine o se restablezca el almacenamiento. Cualquier persona con acceso a ese perfil del navegador puede verlos; no guardes información confidencial. Los registros técnicos se conservan conforme a la configuración y las necesidades operativas del alojamiento. Las comunicaciones que recibamos se conservan durante la atención del asunto y, cuando corresponda, por obligaciones legales. Limitamos el acceso a la información a quienes necesitan atenderla.</p>
    <p>Desde Mi cuenta puedes consultar y modificar los datos de tu identidad, administrar sesiones y solicitar la eliminación mediante las opciones disponibles. También puedes ejercer tus derechos por nuestro correo de contacto. Borrar la demo o desinstalar la PWA no elimina tu cuenta de Clerk; cerrar sesión tampoco borra automáticamente los datos locales de demostración.</p>
    <h2>7. Tus derechos y decisiones</h2><p>Puedes solicitar acceso, rectificación, cancelación u oposición al tratamiento de tus datos, revocar el consentimiento cuando sea aplicable o limitar su uso y divulgación. Escribe a <a href="mailto:luisdelator@vmomentums.info?subject=Solicitud%20de%20privacidad">luisdelator@vmomentums.info</a> indicando tu nombre, un medio para responder, el derecho que deseas ejercer y la información relacionada. Si necesitamos verificar tu identidad o representación, te indicaremos un medio adecuado; no envíes documentos sensibles sin que te los solicitemos.</p><p>Atenderemos tu solicitud conforme a los requisitos y plazos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. Cuando corresponda, te comunicaremos el resultado dentro de 20 días y haremos efectivo lo procedente dentro de los 15 días siguientes, con las extensiones que permita la ley. La cancelación o revocación puede estar sujeta a obligaciones de conservación.</p>
    <h2>8. Cambios a este aviso</h2><p>Publicaremos cualquier modificación en esta página con su fecha de actualización. Antes de añadir analítica u otras finalidades, actualizaremos este aviso y solicitaremos el consentimiento cuando corresponda.</p>
  </LegalShell>;
}
