import type { Metadata } from "next";
import { LegalShell } from "@/ui/site-chrome";
export const metadata: Metadata = { title: "Aviso de Privacidad", alternates: { canonical: "/privacidad" } };
export default function PrivacyPage() {
  return <LegalShell><p className="legal-eyebrow">TU INFORMACIÓN, CON CLARIDAD</p><h1>Aviso de Privacidad</h1><p className="legal-date">Última actualización: 16 de septiembre de 2026</p>
    <div className="legal-notice">Puedes descubrir y buscar eventos sin crear una cuenta. Este sitio no cobra, no emite boletos y no recibe datos de tarjetas bancarias.</div>
    <h2>1. Responsable y contacto</h2><p>Colectivo Mass S.A. de C.V. es responsable de los datos tratados mediante events.alliving.live, denominado ALL LIVING Eventos. Para consultas de privacidad, escribe a <a href="mailto:luisdelator@vmomentums.info">luisdelator@vmomentums.info</a>.</p>
    <h2>2. Qué información se trata</h2><p>Al visitar el sitio, la infraestructura de alojamiento de Vercel procesa datos técnicos como dirección IP, tipo de navegador, fecha, ruta solicitada y registros de errores para entregar las páginas, mantener su seguridad y diagnosticar fallas. Las direcciones de búsqueda pueden incluir el texto y los filtros que elegiste.</p><p>El buscador recibe palabras clave, ciudad, fecha y categoría. Estos criterios se envían desde nuestro servidor a la API de Ticketmaster para consultar la cartelera. No solicitamos tu nombre, correo, ubicación precisa, identificaciones ni información financiera para buscar. Evita escribir datos personales en el buscador.</p><p>Si nos escribes voluntariamente por correo, tratamos tu dirección, el contenido del mensaje y los datos que decidas adjuntar para responder y dar seguimiento a tu solicitud. No pedimos datos sensibles.</p>
    <h2>3. Finalidades</h2><p>Utilizamos la información para mostrar y buscar eventos, operar y proteger el sitio, resolver incidencias y atender consultas o solicitudes de privacidad. No la utilizamos para crear perfiles publicitarios ni para enviar promociones.</p>
    <h2>4. Analítica, cookies y aplicación instalable</h2><p>Esta versión no incorpora Google Analytics, Vercel Web Analytics, píxeles publicitarios ni seguimiento de afiliados. No instala cookies propias para identificar visitantes ni usa inicio de sesión. La infraestructura de seguridad puede procesar señales técnicas para prevenir abuso.</p><p>Si tu navegador admite la aplicación instalable, un service worker conserva en tu dispositivo únicamente recursos básicos, íconos y una pantalla sin conexión. No almacena tu historial de búsquedas ni boletos. Puedes borrar estos datos desde la configuración del navegador o desinstalar la aplicación. Los resultados de Ticketmaster se conservan temporalmente en el servidor para reducir consultas repetidas: hasta 15 minutos para la cartelera y un minuto para búsquedas.</p>
    <h2>5. Proveedores y enlaces externos</h2><p>Vercel presta el alojamiento y puede procesar datos técnicos fuera de México según su infraestructura. Consulta su <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Aviso de Privacidad</a>. Ticketmaster recibe los criterios necesarios para responder a una búsqueda desde nuestro servidor; no le enviamos un perfil de usuario.</p><p>Al seleccionar “Ver boletos” sales de este sitio y entras a Ticketmaster. La compra y la entrega de información personal o financiera ocurren completamente en Ticketmaster.com o su dominio oficial para México, bajo su <a href="https://privacy.ticketmaster.com.mx/es/privacy-policy" target="_blank" rel="noopener noreferrer">propio Aviso de Privacidad</a>. Sus cookies, formularios, pagos y políticas son independientes. ALL LIVING Eventos no recibe los datos de esa compra.</p>
    <h2>6. Conservación y seguridad</h2><p>No mantenemos una base de datos de visitantes ni cuentas. Los registros técnicos se conservan conforme a la configuración y las necesidades operativas del alojamiento. Las comunicaciones que recibamos se conservan durante la atención del asunto y, cuando corresponda, por obligaciones legales. Limitamos el acceso a la información a quienes necesitan atenderla.</p>
    <h2>7. Tus derechos y decisiones</h2><p>Puedes solicitar acceso, rectificación, cancelación u oposición al tratamiento de tus datos, revocar el consentimiento cuando sea aplicable o limitar su uso y divulgación. Escribe a <a href="mailto:luisdelator@vmomentums.info?subject=Solicitud%20de%20privacidad">luisdelator@vmomentums.info</a> indicando tu nombre, un medio para responder, el derecho que deseas ejercer y la información relacionada. Si necesitamos verificar tu identidad o representación, te indicaremos un medio adecuado; no envíes documentos sensibles sin que te los solicitemos.</p><p>Atenderemos tu solicitud conforme a los requisitos y plazos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. Cuando corresponda, te comunicaremos el resultado dentro de 20 días y haremos efectivo lo procedente dentro de los 15 días siguientes, con las extensiones que permita la ley. La cancelación o revocación puede estar sujeta a obligaciones de conservación.</p>
    <h2>8. Cambios a este aviso</h2><p>Publicaremos cualquier modificación en esta página con su fecha de actualización. Antes de añadir analítica, cuentas u otras finalidades, actualizaremos este aviso y solicitaremos el consentimiento cuando corresponda.</p>
  </LegalShell>;
}
