"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, CalendarDots, Check, Compass, GlobeHemisphereWest, Heart, List, MagnifyingGlass, MapPin, SlidersHorizontal, Sparkle, Star, Waves, ForkKnife, Bank, X, DeviceMobile, Clock, CaretRight } from "@phosphor-icons/react";
import { DEFAULT_SEARCH, MARKETS, imageUrl, priceLabel, purchaseUrl, savedProduct, searchParams, type CatalogResult, type Destination, type Detail, type Experience, type SearchInput } from "@/lib/catalog";

const FAVORITES = "all-living-experiences:favorites:v1";
const nav = [{ href: "/", name: "Explorar", view: "explore", Icon: Compass }, { href: "/destinos", name: "Destinos", view: "destinations", Icon: GlobeHemisphereWest }, { href: "/guardados", name: "Guardados", view: "saved", Icon: Heart }];
const categories = [{ name: "Para ti", q: "", Icon: Sparkle }, { name: "En el agua", q: "snorkel", Icon: Waves }, { name: "Cultura", q: "museo", Icon: Bank }, { name: "Sabores", q: "gastronómico", Icon: ForkKnife }];
function Mark({ large = false }: { large?: boolean }) { return <span className={`brand-mark ${large ? "large" : ""}`} aria-hidden><span /></span>; }
function Modal({ open, close, title, children, wide = false }: { open: boolean; close: () => void; title: string; children: React.ReactNode; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (open && !ref.current?.open) ref.current?.showModal(); else if (!open && ref.current?.open) ref.current.close(); }, [open]);
  return <dialog ref={ref} className={`modal ${wide ? "wide" : ""}`} onClose={close} aria-label={title} onClick={event => { if (event.target === event.currentTarget) close(); }}><header className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Cerrar"><X size={23} /></button></header>{children}</dialog>;
}
const normalize = (text: string) => text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export function CatalogApp({ view, initial = DEFAULT_SEARCH }: { view: "explore" | "destinations" | "saved"; initial?: SearchInput }) {
  const [form, setForm] = useState(initial), [submitted, setSubmitted] = useState(initial);
  const [result, setResult] = useState<CatalogResult | null>(null), [loading, setLoading] = useState(view === "explore"), [error, setError] = useState("");
  const [taxonomy, setTaxonomy] = useState<Destination[]>([]), [taxonomyError, setTaxonomyError] = useState("");
  const [favorites, setFavorites] = useState<Experience[]>([]), [savedReady, setSavedReady] = useState(false);
  const [menu, setMenu] = useState(false), [filters, setFilters] = useState(false), [curated, setCurated] = useState(false);
  const [placeQuery, setPlaceQuery] = useState(""), [placeCount, setPlaceCount] = useState(60), [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<Experience | null>(null), [details, setDetails] = useState<Detail | null>(null), [detailError, setDetailError] = useState("");
  const pending = useRef<AbortController | null>(null), detailPending = useRef<AbortController | null>(null);
  const index = useMemo(() => new Map(taxonomy.map(d => [d.id, d])), [taxonomy]);
  const titleOf = (id: string) => id === "4" ? "Caribe" : index.get(id)?.name ?? MARKETS.find(m => m.id === id)?.name ?? "Tu destino";
  const loadDestinations = useCallback(async () => {
    setTaxonomyError("");
    try { const response = await fetch("/api/destinations"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setTaxonomy(data.items); }
    catch { setTaxonomyError("No pudimos cargar los destinos. Vuelve a intentarlo."); }
  }, []);
  const search = useCallback(async (input: SearchInput) => {
    pending.current?.abort(); const controller = new AbortController(); pending.current = controller;
    setLoading(true); setError(""); setSubmitted(input); setForm(input);
    try { const response = await fetch(`/api/search?${searchParams(input)}`, { signal: controller.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No pudimos consultar el catálogo."); if (!controller.signal.aborted) setResult(data); }
    catch (failure) { if (!controller.signal.aborted) { setError(failure instanceof Error ? failure.message : "Se interrumpió la conexión."); setResult(null); } }
    finally { if (!controller.signal.aborted) setLoading(false); }
  }, []);
  useEffect(() => { void loadDestinations(); if (view === "explore") void search(initial); return () => { pending.current?.abort(); detailPending.current?.abort(); }; }, [initial, loadDestinations, search, view]);
  useEffect(() => {
    try {
      const raw: unknown = JSON.parse(localStorage.getItem(FAVORITES) ?? "[]");
      if (Array.isArray(raw)) setFavorites(raw.filter((item): item is Experience => !!item && typeof item === "object" && typeof item.id === "string" && typeof item.title === "string" && !!purchaseUrl(item.url, "production") && (item.image === null || !!imageUrl(item.image))).slice(0, 80).map(savedProduct));
    } catch { /* Storage is optional; the public catalog works without it. */ }
    setSavedReady(true);
  }, []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(""), 3500); return () => clearTimeout(timer); }, [notice]);
  function save(item: Experience) {
    const exists = favorites.some(f => f.id === item.id);
    if (!exists && favorites.length >= 80) { setNotice("Puedes guardar hasta 80 experiencias en este navegador."); return; }
    const next = exists ? favorites.filter(f => f.id !== item.id) : [...favorites, savedProduct(item)];
    setFavorites(next);
    try { localStorage.setItem(FAVORITES, JSON.stringify(next)); setNotice(exists ? "Experiencia retirada de tus guardados" : "Un buen plan, guardado para después"); }
    catch { setNotice("Guardado durante esta visita. Tu navegador no permite conservarlo al cerrar."); }
  }
  async function openDetail(item: Experience) {
    detailPending.current?.abort(); const controller = new AbortController(); detailPending.current = controller;
    setSelected(item); setDetails(null); setDetailError("");
    try { const response = await fetch(`/api/experiences/${encodeURIComponent(item.id)}`, { signal: controller.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (!controller.signal.aborted) setDetails(data); }
    catch (failure) { if (!controller.signal.aborted) setDetailError(failure instanceof Error ? failure.message : "No pudimos abrir esta experiencia."); }
  }
  function choose(id: string) { void search({ ...form, destination: id, page: 1 }); }
  const countryId = form.destination === "4" ? "4" : index.get(form.destination)?.path.find(id => index.get(id)?.type === "COUNTRY") ?? form.destination;
  const countries = taxonomy.filter(d => d.type === "COUNTRY");
  const specific = taxonomy.filter(d => d.id !== countryId && d.path.includes(countryId));
  const places = taxonomy.filter(d => !placeQuery || normalize(`${d.name} ${d.country}`).includes(normalize(placeQuery)));
  const cards = view === "saved" ? favorites : result?.items ?? [];
  const liked = (id: string) => favorites.some(item => item.id === id);

  return <div className="app">
    <a className="skip" href="#main">Ir al contenido</a>
    <header className="app-header"><button className="icon-button mobile-only" onClick={() => setMenu(true)} aria-label="Abrir menú"><List size={25} /></button><Link className="logo" href="/" aria-label="All Living Experiencias"><Mark /><span>ALL LIVING<small>EXPERIENCIAS</small></span></Link><nav className="desktop-nav" aria-label="Navegación principal">{nav.map(n => <Link key={n.view} href={n.href} aria-current={view === n.view ? "page" : undefined}>{n.name}</Link>)}</nav><div className="header-actions"><span className="open-badge"><span />Acceso libre</span><Link className="icon-button desktop-only" href="/guardados" aria-label={`Guardados, ${favorites.length} experiencias`}><Heart size={23} />{favorites.length > 0 && <b>{favorites.length}</b>}</Link><button className="icon-button" onClick={() => window.dispatchEvent(new Event("catalog:install"))} aria-label="Instalar aplicación"><DeviceMobile size={24} /></button></div></header>
    <div className="mode-strip"><span><i />CATÁLOGO REAL · VIATOR</span><span>Versión de consulta <span className="strip-extra">· entra y explora</span></span></div>
    <main id="main" className="main">
      {view === "explore" ? <>
        <div className="welcome"><div><p className="eyebrow">EL MUNDO ESTÁ LLENO DE BUENOS PLANES</p><h1>Sal de la rutina. <em>Sal a vivir.</em></h1></div><button className="location-pill" onClick={() => document.getElementById("search-form")?.scrollIntoView({ behavior: "smooth", block: "center" })}><MapPin size={17} weight="fill" />{titleOf(submitted.destination)}<CaretRight size={13} /></button></div>
        <section className="discovery-hero" aria-label="Inspírate"><article className="hero-event"><Image src="/demo/cenote.webp" alt="Un cenote entre la vegetación de la Riviera Maya" fill priority sizes="(max-width: 780px) 100vw, 70vw" /><div className="hero-overlay" /><span className="glass-pill"><Sparkle size={14} weight="fill" />MOMENTOS QUE SE QUEDAN CONTIGO</span><div className="hero-copy"><p>EXPLORA · DESCUBRE · VIVE</p><h2>Tu siguiente<br /><em>gran historia.</em></h2><span>Empieza con un “¿y si vamos?”.</span><a href="#catalogo" className="light-button">Encuentra tu experiencia<ArrowUpRight size={20} /></a></div><div className="hero-dots" aria-hidden><i /><i /><i /></div></article><aside className="hero-side"><Link className="world-teaser" href="/destinos"><span className="eyebrow">ELIGE TU ESCENARIO</span><GlobeHemisphereWest className="world-icon" size={175} weight="thin" /><h2>Un mundo.<br /><em>Todos tus planes.</em></h2><footer><span>{taxonomy.length ? `${taxonomy.length.toLocaleString("es-MX")} destinos en Viator` : "Más lugares por descubrir"}<small>Busca países, islas y ciudades</small></span><span className="round-arrow"><ArrowUpRight size={23} /></span></footer></Link><Link className="saved-teaser" href="/guardados"><Heart size={32} weight="duotone" /><span><strong>Tu próxima lista de deseos.</strong><small>Guarda lo que te haga decir “vamos”.</small></span><ArrowUpRight size={19} /></Link></aside></section>
        <section className="markets" aria-label="Destinos destacados"><div><p className="eyebrow">MÁS ALLÁ DE LO DE SIEMPRE</p><h2>¿Dónde nos vemos?</h2></div><div className="market-choices">{MARKETS.map(m => <button key={m.id} onClick={() => choose(m.id)} aria-pressed={form.destination === m.id}><span className="market-code">{m.code}</span><span>{m.name}<small>{m.subtitle}</small></span>{form.destination === m.id && <i />}</button>)}</div></section>
        <section id="catalogo" className="discover-section"><div className="section-heading"><div><p className="eyebrow">HAZLE ESPACIO EN TU VIAJE</p><h2>Esto te va a <em>encantar.</em></h2></div><div className="collection-tabs" aria-label="Colecciones"><button aria-pressed="true">Explorar</button><button onClick={() => setCurated(true)}>Selección All Living</button></div></div>
          <div className="category-tabs" aria-label="Ideas de experiencias">{categories.map(c => <button key={c.name} aria-pressed={submitted.q === c.q} onClick={() => void search({ ...form, q: c.q, page: 1 })}><c.Icon size={19} weight={submitted.q === c.q ? "fill" : "regular"} />{c.name}</button>)}</div>
          <form id="search-form" className="search-panel" onSubmit={event => { event.preventDefault(); void search({ ...form, page: 1 }); }}>
            <div className="destination-inputs"><label>País o región<select aria-label="País o región" value={countryId} onChange={event => setForm({ ...form, destination: event.target.value })}><option value="4">Caribe · todas las islas</option>{!countries.length && <option value={countryId}>{titleOf(countryId)}</option>}{countries.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Ciudad o zona<select aria-label="Ciudad o zona" value={form.destination === countryId ? "" : form.destination} onChange={event => setForm({ ...form, destination: event.target.value || countryId })}><option value="">Todos los destinos</option>{specific.map(d => <option key={d.id} value={d.id}>{d.name}{countryId === "4" && d.country && d.type !== "COUNTRY" ? ` · ${d.country}` : ""}</option>)}</select></label></div>
            <div className="search-row"><label className="search-input"><MagnifyingGlass size={22} /><input aria-label="Buscar experiencia" type="search" value={form.q} maxLength={100} placeholder="Globo, cenotes, museos, ese plan que traes en mente…" onChange={event => setForm({ ...form, q: event.target.value })} /></label><label className="date-input"><CalendarDots size={20} /><input aria-label="Fecha de la experiencia" type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /></label><button className="filter-button" type="button" onClick={() => setFilters(true)}><SlidersHorizontal size={21} /><span>Filtros</span>{(form.cancellation || form.maxPrice !== null) && <i />}</button><button className="primary" type="submit" disabled={loading}>{loading ? "Buscando…" : "Buscar"}<ArrowRight size={18} /></button></div>
          </form>
          {taxonomyError && <p className="inline-error" role="alert">{taxonomyError} <button onClick={() => void loadDestinations()}>Reintentar</button></p>}
          <div className="results-info"><p role="status" aria-live="polite">{loading ? "Encontrando tu próximo gran plan…" : result ? <><strong>{result.total.toLocaleString("es-MX")}</strong> experiencias · {result.destination}{submitted.q ? ` · “${submitted.q}”` : ""}</> : ""}{result && !loading && result.mode === "sandbox" && <span> · catálogo de pruebas</span>}</p><label>Ordenar:<select aria-label="Ordenar experiencias" value={submitted.sort} onChange={event => void search({ ...submitted, sort: event.target.value, page: 1 })}><option value="recommended">Destacados de Viator</option><option value="price">Menor precio base</option><option value="rating">Mejor calificación</option><option value="duration">Menor duración</option></select></label></div>
          {(submitted.date || submitted.q || submitted.cancellation || submitted.maxPrice !== null) && <div className="applied-filters"><span>{submitted.date || "Cualquier fecha"}{submitted.cancellation ? " · Cancelación gratuita" : ""}{submitted.maxPrice !== null ? ` · Precio base hasta ${priceLabel(submitted.maxPrice, submitted.currency)}` : ""}</span><button onClick={() => void search({ ...DEFAULT_SEARCH, destination: submitted.destination, currency: submitted.currency })}>Limpiar filtros<X size={14} /></button></div>}
        </section>
      </> : view === "destinations" ? <>
        <div className="page-title"><p className="eyebrow">ELIGE TU PRÓXIMA HISTORIA</p><h1>El mundo se vive<br /><em>destino a destino.</em></h1><p>Busca cualquier país, isla, región o ciudad que Viator tenga en su catálogo.</p></div><div className="market-directory">{MARKETS.map(m => <Link key={m.id} href={`/?destination=${m.id}`}><span className="market-code">{m.code}</span><strong>{m.name}</strong><ArrowUpRight size={20} /></Link>)}<div className="pending-destination"><span className="market-code">VE</span><strong>Venezuela</strong><small>Sin cobertura en este catálogo por ahora</small></div></div>
        <label className="destination-search"><MagnifyingGlass size={22} /><input aria-label="Buscar destino" placeholder="Madrid, Buenos Aires, Cartagena, Aruba…" type="search" value={placeQuery} onChange={event => { setPlaceQuery(event.target.value); setPlaceCount(60); }} /></label><p className="directory-count" role="status">{taxonomyError ? taxonomyError : taxonomy.length ? `${places.length.toLocaleString("es-MX")} destinos encontrados` : "Consultando destinos…"}</p>{taxonomyError && <button className="secondary" onClick={() => void loadDestinations()}>Reintentar</button>}<div className="destination-grid">{places.slice(0, placeCount).map(d => <Link key={d.id} href={`/?destination=${d.id}`}><span><MapPin size={21} weight="duotone" /></span><div><strong>{d.name}</strong><small>{d.country && d.country !== d.name ? d.country : d.type === "COUNTRY" ? "Explora todo el país" : "Explora este destino"}</small></div><ArrowUpRight size={16} /></Link>)}</div>{places.length > placeCount && <button className="secondary more-destinations" onClick={() => setPlaceCount(n => n + 60)}>Ver más destinos<ArrowRight size={17} /></button>}
      </> : <div className="page-title"><p className="eyebrow">LOS PLANES QUE TE EMOCIONAN</p><h1>Tu lista de<br /><em>“tenemos que ir”.</em></h1><p>Guardados en este navegador, sin cuenta. Confirma precios y disponibilidad al volver a consultar Viator.</p></div>}

      {view !== "destinations" && <section aria-label="Experiencias" aria-busy={loading || view === "saved" && !savedReady}>
        {loading || view === "saved" && !savedReady ? <div className="experience-grid" aria-label="Cargando experiencias">{[1, 2, 3, 4, 5, 6].map(i => <div className="skeleton" key={i}><div /><p /><p /></div>)}</div>
          : error ? <div className="empty" role="alert"><Compass size={42} /><h2>El plan sigue ahí.</h2><p>{error}</p><button className="primary" onClick={() => void search(submitted)}>Volver a intentar<ArrowRight size={17} /></button></div>
            : cards.length === 0 ? <div className="empty"><Heart size={42} weight="duotone" /><h2>{view === "saved" ? "Todo empieza con un flechazo." : "Probemos otro plan."}</h2><p>{view === "saved" ? "Toca el corazón de una experiencia y vuelve a encontrarla aquí." : "Viator no devolvió experiencias con esta combinación. Prueba otra fecha o cambia los filtros."}</p>{view === "saved" ? <Link className="primary" href="/">Explorar experiencias<ArrowRight size={17} /></Link> : <button className="primary" onClick={() => void search({ ...DEFAULT_SEARCH, destination: submitted.destination })}>Quitar filtros</button>}</div>
              : <div className="experience-grid">{cards.map(item => <article key={item.id} className="experience-card"><div className="tile-image"><button className="image-open" onClick={() => void openDetail(item)} aria-label={`Ver detalles de ${item.title}`}>{item.image ? <Image src={item.image} alt={item.title} fill sizes="(max-width: 620px) 100vw, (max-width: 1050px) 50vw, 33vw" unoptimized /> : <Compass size={60} weight="thin" />}</button>{item.freeCancellation && <span className="tile-badge"><Check size={12} />Cancelación gratuita</span>}<button className="favorite-button" aria-label={`${liked(item.id) ? "Quitar de guardados" : "Guardar"}: ${item.title}`} aria-pressed={liked(item.id)} onClick={() => save(item)}><Heart size={22} weight={liked(item.id) ? "fill" : "regular"} /></button></div><div className="tile-body"><div className="tile-meta"><span><MapPin size={12} />{index.get(item.destination)?.name ?? (view === "explore" ? result?.destination : "Experiencia")}</span>{item.rating !== null && item.reviews > 0 && <span className="rating"><Star size={13} weight="fill" /><strong>{item.rating.toFixed(1)}</strong><small>({item.reviews.toLocaleString("es-MX")})</small></span>}</div><h3><button onClick={() => void openDetail(item)}>{item.title}</button></h3>{item.duration && <p className="duration"><Clock size={13} />{item.duration}</p>}<p className="description">{item.description}</p><div className="tile-bottom"><div><small>{item.fromPrice !== null ? "Desde" : "Planea tu visita"}</small><strong>{item.fromPrice !== null && item.currency ? priceLabel(item.fromPrice, item.currency) : "Ver experiencia"}</strong></div><button className="round-arrow" aria-label={`Abrir ${item.title}`} onClick={() => void openDetail(item)}><ArrowUpRight size={24} /></button></div>{item.extraCharges !== null && item.extraCharges > 0 && item.currency && <p className="extra-charges">Incluye hasta {priceLabel(item.extraCharges, item.currency)} de cargos a pagar en destino.</p>}{item.sources.length > 0 && <small className="review-sources">Opiniones de {item.sources.join(" y ")}</small>}</div></article>)}</div>}
      </section>}
      {view === "explore" && result && !loading && result.pages > 1 && <nav className="pagination" aria-label="Páginas del catálogo"><button disabled={result.page <= 1} onClick={() => { void search({ ...submitted, page: result.page - 1 }); document.getElementById("catalogo")?.scrollIntoView({ block: "start" }); }}>Anterior</button><span>Página {result.page} de {result.pages.toLocaleString("es-MX")}</span><button disabled={result.page >= result.pages} onClick={() => { void search({ ...submitted, page: result.page + 1 }); document.getElementById("catalogo")?.scrollIntoView({ block: "start" }); }}>Siguiente<ArrowRight size={16} /></button></nav>}
      {view === "explore" && <><p className="catalog-disclosure">Precios orientativos publicados por Viator. La fecha, la opción y los viajeros pueden cambiar el importe final. La reserva y el pago se completan en Viator. El orden por precio usa el precio base del proveedor; las tarjetas incluyen los cargos en destino informados.</p><section className="bottom-banner"><div><p className="eyebrow">LOS BUENOS VIAJES EMPIEZAN CON CURIOSIDAD</p><h2>Haz que tu próximo<br />“algún día” sea <em>pronto.</em></h2></div><Link className="primary" href="/destinos">Explorar destinos<ArrowUpRight size={20} /></Link><Sparkle size={120} weight="thin" aria-hidden /></section></>}
    </main>
    <footer className="app-footer"><span>ALL LIVING Experiencias · Colectivo Mass S.A. de C.V.</span><nav><Link href="/informacion">Cómo funciona y privacidad</Link><a href="mailto:luisdelator@vmomentums.info">Contacto</a></nav></footer>
    <nav className="tabbar" aria-label="Navegación móvil" data-vulcano-bottomnav>{nav.map(n => <Link key={n.view} href={n.href} aria-current={view === n.view ? "page" : undefined}><span>{n.view === "explore" ? <Mark /> : <n.Icon size={25} weight={view === n.view ? "fill" : "regular"} />}</span><small>{n.name}</small></Link>)}<button onClick={() => window.dispatchEvent(new Event("catalog:install"))}><span><DeviceMobile size={25} /></span><small>Instalar</small></button></nav>
    <Modal open={menu} close={() => setMenu(false)} title="Tu próximo gran plan"><div className="drawer-welcome"><Mark large /><h3>Bienvenido a All Living.</h3><p>Un mundo de experiencias, abierto para ti.</p></div><nav className="drawer-nav">{nav.map(n => <Link key={n.view} href={n.href} onClick={() => setMenu(false)}><n.Icon size={24} weight="duotone" />{n.name}<ArrowUpRight size={18} /></Link>)}<Link href="/informacion"><Compass size={24} />Cómo funciona<ArrowUpRight size={18} /></Link></nav></Modal>
    <Modal open={filters} close={() => setFilters(false)} title="Encuentra tu tipo de plan"><form className="filter-fields" onSubmit={event => { event.preventDefault(); setFilters(false); void search({ ...form, page: 1 }); }}><label>Moneda<select aria-label="Moneda del catálogo" value={form.currency} onChange={event => setForm({ ...form, currency: event.target.value, maxPrice: null })}><option value="MXN">Pesos mexicanos · MXN</option><option value="USD">Dólares · USD</option><option value="EUR">Euros · EUR</option></select></label><label>Precio base máximo · {form.currency}<input aria-label="Precio base máximo" type="number" min="1" max="1000000" placeholder="Cualquier precio" value={form.maxPrice ?? ""} onChange={event => setForm({ ...form, maxPrice: event.target.value ? Number(event.target.value) : null })} /></label><label className="check-field"><input type="checkbox" checked={form.cancellation} onChange={event => setForm({ ...form, cancellation: event.target.checked })} />Solo con cancelación gratuita</label><p>El presupuesto filtra el precio base. Algunos planes tienen cargos adicionales en destino, que verás indicados en su tarjeta.</p><button className="primary" type="submit">Aplicar filtros<ArrowRight size={18} /></button></form></Modal>
    <Modal open={curated} close={() => setCurated(false)} title="Selección All Living"><div className="curated-note"><Sparkle size={42} weight="duotone" /><h3>Lo especial lleva nuestra selección.</h3><p>Aquí reuniremos las experiencias curadas por All Living. Esta colección todavía está en preparación.</p><p>El catálogo que puedes recorrer hoy corresponde a las experiencias publicadas por Viator.</p><button className="primary" onClick={() => setCurated(false)}>Seguir explorando<ArrowRight size={18} /></button></div></Modal>
    <Modal open={!!selected} close={() => { detailPending.current?.abort(); setSelected(null); }} title="Tu próxima experiencia" wide>
      {selected && <>{detailError ? <div className="empty" role="alert"><p>{detailError}</p><button className="primary" onClick={() => void openDetail(selected)}>Reintentar</button></div> : !details ? <div className="detail-loading" role="status"><Mark large /><p>Abriendo todos los detalles…</p></div> : <div className="detail-content"><div className="detail-gallery">{details.images.slice(0, 4).map((url, i) => <div key={url}><Image src={url} alt={`${details.title} · imagen ${i + 1}`} fill unoptimized sizes={i === 0 ? "(max-width: 700px) 90vw, 650px" : "(max-width: 700px) 40vw, 220px"} /></div>)}</div><div className="detail-top"><div><p className="eyebrow">{index.get(selected.destination)?.name ?? "DESCUBRE CON VIATOR"}</p><h2>{details.title}</h2></div><button className="icon-button favorite-detail" onClick={() => save(selected)} aria-label={liked(selected.id) ? "Quitar experiencia de guardados" : "Guardar experiencia"}><Heart size={27} weight={liked(selected.id) ? "fill" : "regular"} /></button></div>{details.supplier && <p className="supplier">Operado por {details.supplier}</p>}<p className="detail-description">{details.description}</p><div className="detail-columns"><section><h3>Qué incluye</h3>{details.inclusions.length ? <ul>{details.inclusions.map((s, i) => <li key={i}><Check size={17} /><span>{s}</span></li>)}</ul> : <p>Consulta los detalles de la opción elegida en Viator.</p>}{details.exclusions.length > 0 && <><h3>No incluido</h3><ul>{details.exclusions.map((s, i) => <li key={i}><X size={16} /><span>{s}</span></li>)}</ul></>}</section><section><h3>Antes de ir</h3>{details.additionalInfo.length ? <ul>{details.additionalInfo.map((s, i) => <li key={i}>{s}</li>)}</ul> : <p>Revisa los requisitos de la experiencia al reservar.</p>}<h3>Cancelaciones</h3><p>{details.cancellation || "Consulta la política de cancelación en Viator antes de reservar."}</p></section></div><div className="detail-booking"><div><small>Consulta fecha, opciones y viajeros</small><strong>{selected.fromPrice !== null && selected.currency ? `Desde ${priceLabel(selected.fromPrice, selected.currency)}` : "Precio actualizado en Viator"}</strong></div><a href={details.url} target="_blank" rel="sponsored noopener noreferrer" className="primary">Ver y reservar en Viator<ArrowUpRight size={20} /></a></div><p className="affiliate-note">La compra se completa en Viator. All Living puede recibir una comisión por reservas realizadas desde sus enlaces.</p></div>}</>}
    </Modal>
    {notice && <div className="toast" role="status"><Check size={18} />{notice}</div>}
  </div>;
}
